version: '3.8'

services:
  # React Dashboard
  dashboard:
    build: 
      context: ./dashboard-react
      dockerfile: Dockerfile
    container_name: ai-agents-react-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    
  # FastAPI Server
  api:
    build: .
    container_name: ai-agents-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: uvicorn api.server:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: ai-agents-network
