# ================================
# Production Override for Docker Compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# ================================

services:
  api:
    restart: always
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        compress: "true"

  dashboard:
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        compress: "true"

  redis:
    restart: always
    profiles:
      - production
      - full
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"
