# ================================
# AI Agents Swarm - Docker Compose Configuration
# ================================

x-common-healthcheck: &common-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  # ================================
  # FastAPI Backend Server
  # ================================
  api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ai-agents-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      <<: *common-healthcheck
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M,mode=1777
      - /app/logs:size=50M,mode=1777
    networks:
      - ai-agents-network

  # ================================
  # React Dashboard Frontend
  # ================================
  dashboard:
    build: 
      context: ./dashboard-react
      dockerfile: Dockerfile
      target: production
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    container_name: ai-agents-react-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - API_BASE_URL=http://api:8000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      <<: *common-healthcheck
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=50M,mode=1777
      - /app/.next/cache:size=100M,mode=1777
    networks:
      - ai-agents-network

# ================================
# Networks
# ================================
networks:
  ai-agents-network:
    name: ai-agents-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
